// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fulltext.Context;

namespace fulltext.Migrations
{
    [DbContext(typeof(CatalogoContext))]
    partial class CatalogoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fulltext.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("Observacao")
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Neurologia",
                            Observacao = "a especialidade de neurologia irá cuidar da saúde do seu cérebro."
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Clínica médica",
                            Observacao = "o médico que irá cuidar de você e te fazer os encaminhamentos necessários para os especialistas."
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "PCR Covid19",
                            Observacao = "Exame PCR para constatar se você está infectado pelo coronavírus. "
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Checkup",
                            Observacao = "Um pacote criado com o intuito de fornecer todos os exames necessários para se fazer um check-up em apenas uma compra."
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Hemograma com plaquetas",
                            Observacao = ""
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Gestantes",
                            Observacao = "Pacote exclusivo para ser comprado por gestantes"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Ouro",
                            Observacao = "Assinatura mais top da plataforma, do tipo ouro que fornece 1 consulta por mês gratuitamente."
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Telemedicina",
                            Observacao = "Consulta com o médico através de videochamada."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
